name: Sync Data to R2

on:
  push:
    paths:
      - "data/**"   # only run when files in data folder change
  workflow_dispatch:
    inputs:
      folder:
        description: 'Folder to sync'
        required: true
        default: 'data/'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}
          endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          EOF

      - name: Sync data folder to R2
        run: rclone sync ./data r2:psyence --progress
